import java.util.Arrays;
import java.util.Collections;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String args[]){
        if (args.length < 1) {
            System.out.println("Usage: Reverser string1,string2,string3");
            return;
        }
        String[] input = args[0].split(",");
        System.out.println(Arrays.toString(reverseArrayInPlace(input)));
    }

    public static String[] reverseArrayInPlace(String[] arrayToReverse) {
        int start = 0;
        int end = arrayToReverse.length-1;

        while(start < end) {
            String tempStart = arrayToReverse[start];
            arrayToReverse[start] = arrayToReverse[end];
            arrayToReverse[end] = tempStart;
            start ++;
            end --;
        }

        return arrayToReverse;
    }

    public static void cheat(String[] arrayToReverse) {
        Collections.reverse(Arrays.asList(arrayToReverse));
    }
}
